export const LOGIN= 'LOGIN'

export const ADD_CAR_ALQUILER= 'ADD_CAR_ALQUILER'

export const LIST_CARS= 'LIST_CARS'
export const LIST_CARS_SUCCESS= 'LIST_CARS_SUCCESS'

export const LIST_CARS_ALQUILADOS= 'LIST_CARS_ALQUILADOS'
export const LIST_CARS_ALQUILADOS_SUCCESS= 'LIST_CARS_ALQUILADOS_SUCCESS'

export const GET_CARS = 'GET_CARS'
export const GET_CARS_SUCCESS = 'GET_CARS_SUCCESS'

export const GET_RATING_CARS = 'GET_RATING_CARS'
export const GET_RATING_CARS_SUCCESS = 'GET_RATING_CARS_SUCCESS'

export const LIST_LOCATIONS= 'LIST_LOCATIONS'
export const LIST_LOCATIONS_SUCCESS= 'LIST_LOCATIONS_SUCCESS'

export const LIST_USERS = 'LIST_USERS'
export const LIST_USERS_SUCCESS = 'LIST_USERS_SUCCESS'

export const EDIT_PROFILE = 'EDIT_PROFILE'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'

export const RESERVE = 'RESERVE'
export const RESERVE_SUCCESS = 'RESERVE_SUCCESS'

export const GET_RESERVA = 'GET_RESERVA'
export const GET_RESERVA_SUCCESS = 'GET_RESERVA_SUCCESS'

export const RESET_RESERVA = 'RESET_RESERVA'

export const GET_RESERVAS = 'GET_RESERVAS'
export const GET_RESERVAS_SUCCESS = 'GET_RESERVAS_SUCCESS'

export const SEND_FEEDBACK = 'SEND_FEEDBACK'
export const SEND_FEEDBACK_SUCCESS = 'SEND_FEEDBACK_SUCCESS'

export const UPLOAD_USER = 'SEND_FEEDBACK'
export const UPLOAD_USER_SUCCESS = 'SEND_FEEDBACK_SUCCESS'